//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL_System.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESL_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap admissions_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("admissions_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap calc_64 {
            get {
                object obj = ResourceManager.GetObject("calc_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ESLTemplate&gt;
        ///  &lt;Term Name=&quot;mid-Term&quot; Weight=&quot;50&quot; InputStartTime=&quot;2018/04/16 00:00&quot; InputEndTime=&quot;2018/04/22 23:59&quot;&gt;
        ///    &lt;Subject Name=&quot;Language Art&quot; Weight=&quot;50&quot;&gt;
        ///      &lt;Assessment Name=&quot;In-Class Score&quot; Weight=&quot;50&quot; TeacherSequence=&quot;1&quot; Type=&quot;Score&quot;  AllowCustomAssessment=&quot;true&quot; &gt;&lt;/Assessment&gt;
        ///      &lt;Assessment Name=&quot;Reading Project&quot; Weight=&quot;50&quot; TeacherSequence=&quot;1&quot; Type=&quot;Score&quot;  AllowCustomAssessment=&quot;true&quot; &gt;&lt;/Assessment&gt;
        ///      &lt;Assessment Name=&quot;Homework Completion&quot; Weight=&quot;0&quot; TeacherSequence=&quot;1&quot; Type=&quot;I [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Description_Example {
            get {
                return ResourceManager.GetString("Description_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] ESL課程班級取前N名_樣板_ {
            get {
                object obj = ResourceManager.GetObject("ESL課程班級取前N名_樣板_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] FinalReport {
            get {
                object obj = ResourceManager.GetObject("FinalReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] FinalReport_MailMergeList {
            get {
                object obj = ResourceManager.GetObject("FinalReport_MailMergeList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap meeting_refresh_64 {
            get {
                object obj = ResourceManager.GetObject("meeting_refresh_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] MidReport {
            get {
                object obj = ResourceManager.GetObject("MidReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] MidReport_MailMergeList {
            get {
                object obj = ResourceManager.GetObject("MidReport_MailMergeList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] SemesterReport {
            get {
                object obj = ResourceManager.GetObject("SemesterReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] SemesterReport_MailMergeList {
            get {
                object obj = ResourceManager.GetObject("SemesterReport_MailMergeList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ScoreMappingList&gt;
        ///	&lt;ScoreMapping EngName=&quot;A+&quot; Score=&quot;90&quot;&gt;&lt;/ScoreMapping&gt;
        ///	&lt;ScoreMapping EngName=&quot;A&quot; Score=&quot;80&quot;&gt;&lt;/ScoreMapping&gt;
        ///	&lt;ScoreMapping EngName=&quot;B&quot; Score=&quot;70&quot;&gt;&lt;/ScoreMapping&gt;
        ///	&lt;ScoreMapping EngName=&quot;C&quot; Score=&quot;60&quot;&gt;&lt;/ScoreMapping&gt;
        ///	&lt;ScoreMapping EngName=&quot;D&quot; Score=&quot;&quot;&gt;&lt;/ScoreMapping&gt;
        ///&lt;/ScoreMappingList&gt; 的當地語系化字串。
        /// </summary>
        internal static string 預設ESL等第對照表 {
            get {
                return ResourceManager.GetString("預設ESL等第對照表", resourceCulture);
            }
        }
    }
}
